[package]
name = "http-sock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.24.2"
rsocket_rust = "0.7.2"
